#!/usr/bin/env bash
set -e
set -u
set -o pipefail

is_light="$(echo "$1" '>' .5 | bc)"

if [ "$is_light" -eq 1 ]; then
  value=false
else
  value=true
fi

osascript -e "tell application \"System Events\" to tell appearance preferences to set dark mode to $value"
