#!/usr/bin/env bash
set -e
set -u
set -o pipefail

current_window="$(tmux display-message -p '#I')"
list_of_windows="$(tmux list-windows -a -F '#I #{pane_current_path}' | grep -vE "^$current_window")"
formatted_window_to_select="$(echo "$list_of_windows" | fzf +m --layout=reverse --margin 5%)"
window_index="$(echo "$formatted_window_to_select" | awk '{print $1}')"
tmux select-window -t "$window_index"
