#!/usr/bin/env bash
set -e
set -u
set -o pipefail

is_light="$(echo "$1" '>' .5 | bc)"
if [ "$is_light" -eq 1 ]; then
  theme=theme-colors-light
else
  theme=theme-colors-dark
fi

# I'd normally use XDG_CONFIG_HOME but Alacritty requires absolute
# paths for imports, so I just hard-code ~/.config.
alacritty_dir="$HOME/.config/alacritty"

cp \
  "$alacritty_dir/$theme.toml" \
  "$alacritty_dir/theme-colors.toml"