alias .. cd ..
alias .... cd ../../
alias l ls
alias q exit
alias gpurp 'git pull --rebase && git push'
alias gits 'git s'

alias vi vim

alias agent 'eval `ssh-agent` && ssh-add'

set prompt="\n%c ] "
