if [[ -z "$PS1" ]]; then
  return # quit for non-interactive shells
fi

source "$HOME/.zsh/highlighting.zsh"

source "$HOME/.zsh/options.zsh"

source "$HOME/.zsh/aliases.zsh"

source "$HOME/.zsh/functions.zsh"

source "$HOME/.zsh/prompt.zsh"

if [[ $(uname) = "Linux" ]]; then
  source "$HOME/.zsh/debian.zsh"
fi

if [[ $(uname) = "Darwin" ]]; then
  source "$HOME/.zsh/osx.zsh"
fi

if [[ -e "$HOME/.zshrc_local" ]]; then
  source "$HOME/.zshrc_local"
fi
