if [[ -z "$PS1" ]]; then
	return # quit for non-interactive shells
fi

source ~/.zsh/options.zsh

source ~/.zsh/aliases.zsh

source ~/.zsh/prompt.zsh

source ~/Coding/personal/dotfiles/resources/bin/z.sh

if [[ $(uname) = 'Linux' ]]; then
	source ~/.zsh/linux.zsh
fi

if [[ $(uname) = 'Darwin' ]]; then
	source ~/.zsh/osx.zsh
fi

if [[ -e $HOME/.rvm/scripts/rvm ]]; then
	source $HOME/.rvm/scripts/rvm
fi

if [[ -e $HOME/.zshrc_local ]]; then
	source $HOME/.zshrc_local
fi
