#!/usr/bin/env bash
set -e
set -u
set -o pipefail

is_light="$(echo "$1" '>' .5 | bc)"

if [ "$is_light" -eq 1 ]; then
  bg=colour253
  fg=black
  active_window_bg=colour255
else
  bg=black
  fg=white
  active_window_bg=colour233
fi

tmux set -g status-style "fg=$fg,bg=$active_window_bg"
tmux setw -g window-status-format "#[fg=$fg] #{?window_zoomed_flag,(, }#I#{?window_zoomed_flag,), } #W@#(basename \"#{pane_current_path}\")  #[default]"
tmux setw -g window-status-current-format "#[fg=$bg,bg=$fg] #{?window_zoomed_flag,(, }#I#{?window_zoomed_flag,), } #W@#(basename \"#{pane_current_path}\")  #[default]"
tmux set -g window-status-bell-style "fg=$bg,bg=$fg"
tmux set -g window-style "fg=$fg,bg=$bg"
tmux set -g window-active-style "bg=$active_window_bg"
tmux set -g pane-border-style "fg=$fg,bg=$bg"
tmux set -g pane-active-border-style "fg=$fg,bg=$fg"
tmux set -g window-status-bell-style "fg=$bg,bg=$fg"
