#!/usr/bin/env bash
set -e
set -u
set -o pipefail

is_light="$(echo "$1" '>' .5 | bc)"

XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
mkdir -p "$XDG_CACHE_HOME"
theme_path="$XDG_CACHE_HOME/evanhahn-vim-theme"

if [ "$is_light" -eq 1 ]; then
  echo -n light > "$theme_path"
else
  echo -n dark > "$theme_path"
fi