#!/usr/bin/env bash
set -e
set -u
set -o pipefail

is_light="$(echo "$1" '>' .5 | bc)"

if [ "$is_light" -eq 1 ]; then
  theme='Yaru-light'
else
  theme='Yaru-dark'
fi

gsettings set org.gnome.desktop.interface gtk-theme "$theme"
