alias ~="cd ~"
alias ..="cd .."
alias ....="cd ../.."
alias l="ls"
alias g="git"
alias q="exit"
alias rn="date '+%l:%M%p on %A, %B %e, %Y'"
alias pyserve="python -m SimpleHTTPServer"

alias vi="vim"
alias ed="ed -p:"
alias lynx="lynx -cfg ~/Coding/personal/dotfiles/resources/lynx.cfg"
alias tmux="tmux -u2"

alias ,,="cd .."
alias ..l="cd .. && ls"
alias cd..="cd .."
alias gits="git s"
alias mdkir="mkdir"
alias gut="git"
alias sudp="sudo"
